[package]
name = "onvif"
version = "0.1.0"
authors = ["Chris Bruce <chris@lumeo.com>"]
edition = "2018"
license = "MIT"

[features]
default = ["tls"]
# hyper-rustls does not support IP hosts (like https://192.168.1.2) which are
# very common for IP cameras. So we can use only native-tls for now.
# https://github.com/ctz/hyper-rustls/issues/56
tls = ["reqwest/native-tls"]

[dependencies]
schema = { version = "0.1.0", path = "../schema" }
log = "0.4.11"
xml-rs = "0.8.3"
xmltree = "0.10.2"
yaserde = "0.6.0"
yaserde_derive = "0.6.0"
reqwest = { version = "0.11.0", default-features = false }
digest_auth = "0.2.3"
chrono = "0.4.19"
base64 = "0.13.0"
sha1 = "0.6.0"
url = "2.2.0"
uuid = { version = "0.8.1", features = ["v4"] }
futures-core = "0.3.8"
async-stream = "0.3.0"
async-trait = "0.1.41"
async-recursion = "0.3.1"
num-bigint = "0.3.1"
bigdecimal = "0.2.0"
macro-utils = { git = "https://github.com/lumeohq/xsd-parser-rs", rev = "75806bc" }
xsd-types = { git = "https://github.com/lumeohq/xsd-parser-rs", rev = "75806bc" }
thiserror = "1.0"
tokio = { version = "1.0.1", features = ["time"] }
teloxide = { version = "0.4", features = ["auto-send", "macros"] }
pretty_env_logger = "0.4.0"

[dev-dependencies]
dotenv = "0.15.0"
env_logger = "0.8.2"
futures-util = "0.3.8"
structopt = "0.3.21"
tokio = { version = "1.0.1", features = ["full"] }
